### ISSUE TITLE
Some keys are duplicated

### ISSUE THREAD

**Issue by nvyush** [widgetfactory/jce-language-site#2]
en-GB.com_jce.ini

The keys 'WF_EMOTIONS_TITLE', 'WF_EMOTIONS_DESC' are duplicated.

The key 'WF_EMOTIONS_PERSON_WITH_FOLDED_HAND' does not match the key 'person_with_folded_hand**s**' in the file \components\com_jce\editor\tiny_mce\plugins\emotions\editor_plugin.js

The key WF_DLG_CREATE="Create" is missing.

**Comment by ryandemmer** [comment]
> The keys 'WF_EMOTIONS_TITLE', 'WF_EMOTIONS_DESC' are duplicated.

These are not duplicate keys as they are used in different contexts. The second set is part of the [emotions] section. Sectioned tags are used only in javascript interfaces. The first set of keys is used in the Profile Parameters.

> The key 'WF_EMOTIONS_PERSON_WITH_FOLDED_HAND' does not match the key 'person_with_folded_hands' in the file \components\com_jce\editor\tiny_mce\plugins\emotions\editor_plugin.js

Fixed in commit - https://github.com/widgetfactory/jce-language-site/commit/305c29d0b07260aa42ec43b5cbe485fa40378062
